set_property PACKAGE_PIN W5 [get_ports clock_i]
set_property IOSTANDARD LVCMOS33 [get_ports clock_i]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clock_i]
set_property PACKAGE_PIN V17 [get_ports reset_i]
set_property IOSTANDARD LVCMOS33 [get_ports reset_i]
set_property PACKAGE_PIN V16 [get_ports reset_wz_i]
set_property IOSTANDARD LVCMOS33 [get_ports reset_wz_i]
set_property PACKAGE_PIN U16 [get_ports locked_o]
set_property IOSTANDARD LVCMOS33 [get_ports locked_o]
set_property PACKAGE_PIN E19 [get_ports ack_debug_o]
set_property IOSTANDARD LVCMOS33 [get_ports ack_debug_o]
set_property PACKAGE_PIN U19 [get_ports end_send_data_o]
set_property IOSTANDARD LVCMOS33 [get_ports end_send_data_o]
set_property PACKAGE_PIN B18 [get_ports rx_data_i]
set_property IOSTANDARD LVCMOS33 [get_ports rx_data_i]
set_property PACKAGE_PIN A18 [get_ports tx_data_o]
set_property IOSTANDARD LVCMOS33 [get_ports tx_data_o]